export enum AllTasksActions {
  SET_ALL_TASKS = "SET_ALL_TASKS",
  BROWSER_SUPPORT_INDEXED_DB = "BROWSER_SUPPORT_INDEXED_DB",
  DATABASE_NOT_OPENED = "DATABASE_NOT_OPENED",
  UPDATE_TASK = "UPDATE_TASK",
  DELETE_TASK = "DELETE_TASK",
  DELETE_FINISHED_TASK = "DELETE_FINISHED_TASK",
}
